services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nextjs_app

    ports:
      - "3000:3000"
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/mydb
      UPLOADTHING_TOKEN: token
      BETTER_AUTH_SECRET: Rey6zbwVyhDGg4dgB4qx/Ojr279dK18mE9eo4yNC3Zs=
      BETTER_AUTH_URL: http://localhost:3000
      GITHUB_CLIENT_ID: 
      GITHUB_CLIENT_SECRET:
    volumes:
      - ./:/app
      - /app/node_modules

    depends_on:
      - db

    # command: npm run dev -- --hostname 0.0.0.0
    develop:
      watch:
        # package.json → rebuild completo
        - action: rebuild
          path: ./package.json

        # package-lock.json → también rebuild
        - action: rebuild
          path: ./package-lock.json

        # Todo lo demás → sync
        - action: sync
          path: ./
          target: /app

  db:
    image: postgres:18

    container_name: postgres_db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: